2021-09-29 03:47:27 INFO     STATUS => selesai
2021-09-29 03:52:11 INFO     STATUS => selesai
2021-09-29 03:52:11 INFO     PAYLOAD => 
2021-09-29 03:55:26 INFO     STATUS => selesai
2021-09-29 03:55:26 INFO     PAYLOAD => 
2021-09-29 12:43:12 INFO     halo
2021-09-29 12:43:13 INFO     -----------------------------
2021-09-29 12:43:13 INFO     Predict Start
2021-09-29 12:43:13 INFO     Recognizer start
2021-09-29 12:43:13 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 12:43:13 INFO     success 0 - 96.20758479684426
2021-09-29 12:43:13 INFO     STATUS => mulai
2021-09-29 12:44:53 INFO     halo
2021-09-29 12:44:53 INFO     -----------------------------
2021-09-29 12:44:53 INFO     Predict Start
2021-09-29 12:44:53 INFO     Recognizer start
2021-09-29 12:44:53 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 12:44:53 INFO     success 0 - 96.20758479684426
2021-09-29 12:44:53 INFO     STATUS => mulai
2021-09-29 12:46:47 INFO     STATUS => mulai
2021-09-29 12:46:47 INFO     STATUS => selesai
2021-09-29 12:52:38 INFO     halo
2021-09-29 12:52:38 INFO     -----------------------------
2021-09-29 12:52:38 INFO     Predict Start
2021-09-29 12:52:38 INFO     Recognizer start
2021-09-29 12:52:39 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 12:52:39 INFO     success 0 - 96.20758479684426
2021-09-29 12:52:39 INFO     STATUS => mulai
2021-09-29 12:53:47 INFO     halo
2021-09-29 12:53:47 INFO     -----------------------------
2021-09-29 12:53:47 INFO     Predict Start
2021-09-29 12:53:47 INFO     Recognizer start
2021-09-29 12:53:47 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 12:53:47 INFO     success 0 - 96.20758479684426
2021-09-29 12:53:47 INFO     STATUS => mulai
2021-09-29 12:57:55 INFO     halo
2021-09-29 12:57:55 INFO     -----------------------------
2021-09-29 12:57:55 INFO     Predict Start
2021-09-29 12:57:55 INFO     Recognizer start
2021-09-29 12:57:55 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 12:57:55 INFO     success 0 - 96.20758479684426
2021-09-29 12:57:55 INFO     STATUS => mulai
2021-09-29 13:00:04 INFO     halo
2021-09-29 13:00:04 INFO     -----------------------------
2021-09-29 13:00:04 INFO     Predict Start
2021-09-29 13:00:04 INFO     Recognizer start
2021-09-29 13:00:05 INFO     Predict result: 0 with 70.01464489803584 distance
2021-09-29 13:00:05 INFO     success 0 - 70.01464489803584
2021-09-29 13:00:05 INFO     STATUS => mulai
2021-09-29 13:02:17 INFO     halo
2021-09-29 13:02:17 INFO     -----------------------------
2021-09-29 13:02:17 INFO     Predict Start
2021-09-29 13:02:18 INFO     Recognizer start
2021-09-29 13:02:18 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 13:02:18 INFO     success 0 - 96.20758479684426
2021-09-29 13:02:18 INFO     STATUS => mulai
2021-09-29 13:02:18 ERROR    Exception on /recognize/predict [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 87, in predict
    record.put()
  File "/home/ubuntu/skripsi/file_downloader.py", line 99, in put
    logging.info('PARAMS => confidence: ', self.confidende)
AttributeError: 'putData' object has no attribute 'confidende'
2021-09-29 13:03:05 INFO     halo
2021-09-29 13:03:05 INFO     -----------------------------
2021-09-29 13:03:05 INFO     Predict Start
2021-09-29 13:03:05 INFO     Recognizer start
2021-09-29 13:03:06 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 13:03:06 INFO     success 0 - 96.20758479684426
2021-09-29 13:03:06 INFO     STATUS => mulai
2021-09-29 13:03:06 ERROR    Exception on /recognize/predict [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 87, in predict
    record.put()
  File "/home/ubuntu/skripsi/file_downloader.py", line 101, in put
    response = dynamodb.put_item(
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Item.confidence.S, value: 31.280296573682676, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.face_id.S, value: 0, type: <class 'int'>, valid types: <class 'str'>
2021-09-29 13:04:23 INFO     halo
2021-09-29 13:04:23 INFO     -----------------------------
2021-09-29 13:04:23 INFO     Predict Start
2021-09-29 13:04:23 INFO     Recognizer start
2021-09-29 13:04:23 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 13:04:23 INFO     success 0 - 96.20758479684426
2021-09-29 13:04:24 INFO     STATUS => mulai
2021-09-29 13:04:24 INFO     STATUS => selesai
2021-09-29 13:56:01 INFO     halo
2021-09-29 13:56:02 INFO     -----------------------------
2021-09-29 13:56:02 INFO     Predict Start
2021-09-29 13:56:02 INFO     Recognizer start
2021-09-29 13:56:02 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-29 13:56:02 INFO     success 0 - 96.20758479684426
2021-09-29 13:56:02 INFO     STATUS => mulai
2021-09-29 13:56:02 INFO     STATUS => selesai
2021-09-30 06:21:06 INFO     halo
2021-09-30 06:21:06 INFO     -----------------------------
2021-09-30 06:21:06 INFO     Predict Start
2021-09-30 06:21:07 INFO     Recognizer start
2021-09-30 06:21:07 INFO     Predict result: 3 with 110.59606779736681 distance
2021-09-30 06:21:07 INFO     success 3 - 110.59606779736681
2021-09-30 06:22:31 INFO     halo
2021-09-30 06:22:31 INFO     -----------------------------
2021-09-30 06:22:31 INFO     Predict Start
2021-09-30 06:22:31 INFO     Recognizer start
2021-09-30 06:22:32 INFO     Predict result: 3 with 109.35157795147548 distance
2021-09-30 06:22:32 INFO     success 3 - 109.35157795147548
2021-09-30 06:27:39 INFO     halo
2021-09-30 06:27:40 INFO     -----------------------------
2021-09-30 06:27:40 INFO     Predict Start
2021-09-30 06:27:40 INFO     Recognizer start
2021-09-30 06:27:40 INFO     Predict result: 0 with 96.20758479684426 distance
2021-09-30 06:27:40 INFO     success 0 - 96.20758479684426
2021-09-30 06:27:40 INFO     STATUS => mulai
2021-09-30 06:27:40 INFO     STATUS => selesai
2021-09-30 07:06:17 INFO     halo
2021-09-30 07:06:17 INFO     -----------------------------
2021-09-30 07:06:17 INFO     Predict Start
2021-09-30 07:06:17 INFO     Recognizer start
2021-09-30 07:06:18 INFO     Predict result: 3 with 104.83457126912876 distance
2021-09-30 07:06:18 INFO     success 3 - 104.83457126912876
2021-09-30 07:06:18 INFO     STATUS => mulai
2021-09-30 07:06:18 INFO     STATUS => selesai
2021-09-30 07:07:16 INFO     halo
2021-09-30 07:07:16 INFO     -----------------------------
2021-09-30 07:07:16 INFO     Predict Start
2021-09-30 07:07:16 INFO     Recognizer start
2021-09-30 07:07:16 INFO     Predict result: 3 with 110.874505593088 distance
2021-09-30 07:07:16 INFO     success 3 - 110.874505593088
2021-09-30 07:07:16 INFO     STATUS => mulai
2021-09-30 07:07:16 INFO     STATUS => selesai
2021-09-30 08:05:24 INFO     halo
2021-09-30 08:05:24 INFO     -----------------------------
2021-09-30 08:05:24 INFO     Predict Start
2021-09-30 08:05:24 INFO     Recognizer start
2021-09-30 08:05:24 INFO     Predict result: 3 with 110.874505593088 distance
2021-09-30 08:05:24 INFO     success 3 - 110.874505593088
2021-09-30 08:05:24 INFO     STATUS => mulai
2021-09-30 08:05:24 INFO     STATUS => selesai
2021-09-30 08:08:17 INFO     halo
2021-09-30 08:08:17 INFO     -----------------------------
2021-09-30 08:08:17 INFO     Predict Start
2021-09-30 08:08:17 INFO     Recognizer start
2021-09-30 08:08:18 INFO     Predict result: 3 with 106.60174433681932 distance
2021-09-30 08:08:18 INFO     success 3 - 106.60174433681932
2021-09-30 08:16:24 ERROR    Exception on /recognize/train [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 248, in train
    response = make_response({
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/helpers.py", line 191, in make_response
    return current_app.make_response(args)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1713, in make_response
    rv = jsonify(rv)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/json/__init__.py", line 348, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/json/__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/json/__init__.py", line 56, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
2021-09-30 08:17:47 INFO     halo
2021-09-30 08:17:47 INFO     -----------------------------
2021-09-30 08:17:47 INFO     Predict Start
2021-09-30 08:17:47 INFO     Recognizer start
2021-09-30 08:17:47 INFO     Predict result: 1 with 97.45788510638229 distance
2021-09-30 08:17:47 INFO     success 1 - 97.45788510638229
2021-09-30 08:17:47 INFO     STATUS => mulai
2021-09-30 08:17:47 INFO     STATUS => selesai
2021-10-31 04:22:26 INFO     halo
2021-10-31 04:22:27 INFO     -----------------------------
2021-10-31 04:22:27 INFO     Predict Start
2021-10-31 04:22:27 INFO     Recognizer start
2021-10-31 04:22:27 INFO     Predict result: 3 with 90.01684025139761 distance
2021-10-31 04:22:27 INFO     success 3 - 90.01684025139761
2021-10-31 04:22:27 INFO     STATUS => mulai
2021-10-31 04:22:27 INFO     STATUS => selesai
2021-10-31 04:23:35 INFO     halo
2021-10-31 04:23:35 INFO     -----------------------------
2021-10-31 04:23:35 INFO     Predict Start
2021-10-31 04:23:35 INFO     Recognizer start
2021-10-31 04:23:36 INFO     Predict result: 3 with 76.53928628197957 distance
2021-10-31 04:23:36 INFO     success 3 - 76.53928628197957
2021-10-31 04:23:36 INFO     STATUS => mulai
2021-10-31 04:23:36 INFO     STATUS => selesai
2021-11-02 15:31:37 INFO     halo
2021-11-02 15:31:37 INFO     -----------------------------
2021-11-02 15:31:37 INFO     Predict Start
2021-11-02 15:31:37 INFO     Recognizer start
2021-11-02 15:31:38 INFO     Predict result: 3 with 74.43713385667604 distance
2021-11-02 15:31:38 INFO     success 3 - 74.43713385667604
2021-11-02 15:31:38 INFO     STATUS => mulai
2021-11-02 15:31:38 INFO     STATUS => selesai
2021-11-04 01:03:59 INFO     halo
2021-11-04 01:03:59 INFO     -----------------------------
2021-11-04 01:03:59 INFO     Predict Start
2021-11-04 01:03:59 INFO     Recognizer start
2021-11-04 01:03:59 INFO     Predict result: 3 with 74.43713385667604 distance
2021-11-04 01:03:59 INFO     success 3 - 74.43713385667604
2021-11-04 01:03:59 INFO     STATUS => mulai
2021-11-04 01:03:59 INFO     STATUS => selesai
2021-11-04 01:05:16 INFO     halo
2021-11-04 01:05:16 INFO     -----------------------------
2021-11-04 01:05:16 INFO     Predict Start
2021-11-04 01:05:16 INFO     Recognizer start
2021-11-04 01:05:17 INFO     Predict result: 3 with 74.43713385667604 distance
2021-11-04 01:05:17 INFO     success 3 - 74.43713385667604
2021-11-04 01:05:17 INFO     STATUS => mulai
2021-11-04 01:05:17 INFO     STATUS => selesai
2021-11-04 01:08:14 INFO     halo
2021-11-04 01:08:15 INFO     -----------------------------
2021-11-04 01:08:15 INFO     Predict Start
2021-11-04 01:08:15 INFO     Recognizer start
2021-11-04 01:08:15 INFO     Predict result: 1 with 37.03396612689221 distance
2021-11-04 01:08:15 INFO     success 1 - 37.03396612689221
2021-11-04 01:08:15 INFO     STATUS => mulai
2021-11-04 01:08:15 INFO     STATUS => selesai
2021-11-04 01:14:56 INFO     halo
2021-11-04 01:14:56 INFO     -----------------------------
2021-11-04 01:14:56 INFO     Predict Start
2021-11-04 01:14:56 INFO     Recognizer start
2021-11-04 01:14:57 INFO     Predict result: 3 with 44.79737041487379 distance
2021-11-04 01:14:57 INFO     success 3 - 44.79737041487379
2021-11-04 01:15:46 INFO     halo
2021-11-04 01:15:46 INFO     -----------------------------
2021-11-04 01:15:46 INFO     Predict Start
2021-11-04 01:15:46 INFO     Recognizer start
2021-11-04 01:15:47 INFO     Predict result: 1 with 40.35738791446642 distance
2021-11-04 01:15:47 INFO     success 1 - 40.35738791446642
2021-11-04 01:15:47 INFO     STATUS => mulai
2021-11-04 01:15:47 INFO     STATUS => selesai
2021-11-04 01:22:49 INFO     halo
2021-11-04 01:22:49 INFO     -----------------------------
2021-11-04 01:22:49 INFO     Predict Start
2021-11-04 01:22:49 INFO     Recognizer start
2021-11-04 01:22:50 INFO     Predict result: 1 with 48.262579613847855 distance
2021-11-04 01:22:50 INFO     success 1 - 48.262579613847855
2021-11-04 01:22:50 INFO     STATUS => mulai
2021-11-04 01:22:50 INFO     STATUS => selesai
2021-11-04 01:57:17 INFO     halo
2021-11-04 01:57:17 INFO     -----------------------------
2021-11-04 01:57:17 INFO     Predict Start
2021-11-04 01:57:17 INFO     Recognizer start
2021-11-04 01:57:18 INFO     Predict result: 0 with 101.04928824566917 distance
2021-11-04 01:57:18 INFO     success 0 - 101.04928824566917
2021-11-04 01:58:07 INFO     halo
2021-11-04 01:58:07 INFO     -----------------------------
2021-11-04 01:58:07 INFO     Predict Start
2021-11-04 01:58:07 INFO     Recognizer start
2021-11-04 01:58:08 INFO     Predict result: 1 with 104.34309971327261 distance
2021-11-04 01:58:08 INFO     success 1 - 104.34309971327261
2021-11-04 01:58:08 INFO     STATUS => mulai
2021-11-04 01:58:08 INFO     STATUS => selesai
2021-11-04 02:07:04 INFO     halo
2021-11-04 02:07:04 INFO     -----------------------------
2021-11-04 02:07:04 INFO     Predict Start
2021-11-04 02:07:04 INFO     Recognizer start
2021-11-04 02:07:04 INFO     Predict result: 0 with 99.50586925538359 distance
2021-11-04 02:07:04 INFO     success 0 - 99.50586925538359
2021-11-04 02:07:23 INFO     halo
2021-11-04 02:07:24 INFO     -----------------------------
2021-11-04 02:07:24 INFO     Predict Start
2021-11-04 02:07:24 INFO     Recognizer start
2021-11-04 02:07:24 INFO     Predict result: 0 with 87.91822022056795 distance
2021-11-04 02:07:24 INFO     success 0 - 87.91822022056795
2021-11-04 02:12:49 INFO     halo
2021-11-04 02:12:49 INFO     -----------------------------
2021-11-04 02:12:49 INFO     Predict Start
2021-11-04 02:12:49 INFO     Recognizer start
2021-11-04 02:12:49 INFO     Predict result: 1 with 79.2207313751324 distance
2021-11-04 02:12:49 INFO     success 1 - 79.2207313751324
2021-11-04 02:12:49 INFO     STATUS => mulai
2021-11-04 02:12:49 INFO     STATUS => selesai
2021-11-04 02:21:34 INFO     halo
2021-11-04 02:21:34 INFO     -----------------------------
2021-11-04 02:21:34 INFO     Predict Start
2021-11-04 02:21:35 INFO     Recognizer start
2021-11-04 02:21:35 INFO     Predict result: 1 with 74.5375321971192 distance
2021-11-04 02:21:35 INFO     success 1 - 74.5375321971192
2021-11-04 02:21:35 INFO     STATUS => mulai
2021-11-04 02:21:35 INFO     STATUS => selesai
2021-11-04 02:49:51 ERROR    Exception on /update [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 292, in update
    dynamodb_client = updateDataNew(id)
UnboundLocalError: local variable 'id' referenced before assignment
2021-11-04 02:50:09 ERROR    Exception on /update [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 292, in update
    dynamodb_client = updateDataNew(id)
UnboundLocalError: local variable 'id' referenced before assignment
2021-11-04 02:50:28 ERROR    Exception on /update [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 292, in update
    dynamodb_client = updateDataNew(id)
UnboundLocalError: local variable 'id' referenced before assignment
2021-11-04 02:50:33 ERROR    Exception on /update [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 292, in update
    dynamodb_client = updateDataNew(id)
UnboundLocalError: local variable 'id' referenced before assignment
2021-11-04 02:54:42 ERROR    Exception on /update [POST]
Traceback (most recent call last):
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/skripsi/app.py", line 294, in update
    ress = dynamodb_client.update(AttrName,AttrValue, expression)
  File "/home/ubuntu/skripsi/file_downloader.py", line 68, in update
    response = dynamodb.update_item(
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/ubuntu/skripsi/skripsi/lib/python3.8/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Key.id.S, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
